[package]
name = "gluesql-discord-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
gluesql-core = "0.13"
async-trait = "0.1"
serenity = "0.11"

[dev-dependencies]
test-suite = { package = "gluesql-test-suite", version = "0.13" }
tokio = { version = "1", features = ["rt", "macros"] }
